// <auto-generated />
using System;
using Auditor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auditor.Migrations
{
    [DbContext(typeof(AuditorContext))]
    [Migration("20260526164539_AddFieldsToAirport")]
    partial class AddFieldsToAirport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditResponseReason", b =>
                {
                    b.Property<long>("ResponseId")
                        .HasColumnType("bigint")
                        .HasColumnName("response_id");

                    b.Property<long>("ReasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("reason_id");

                    b.HasKey("ResponseId", "ReasonId")
                        .HasName("PK__audit_re__B3AA63C32753E0CD");

                    b.HasIndex("ReasonId");

                    b.ToTable("audit_response_reason", (string)null);
                });

            modelBuilder.Entity("AuditScheduleAuditor", b =>
                {
                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<long>("AuditorId")
                        .HasColumnType("bigint")
                        .HasColumnName("auditor_id");

                    b.HasKey("ScheduleId", "AuditorId")
                        .HasName("PK__audit_sc__BD9E29F05A8F4534");

                    b.HasIndex("AuditorId");

                    b.ToTable("audit_schedule_auditor", (string)null);
                });

            modelBuilder.Entity("AuditSiteTemplate", b =>
                {
                    b.Property<long>("SiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("site_id");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.HasKey("SiteId", "TemplateId")
                        .HasName("PK__audit_si__39CB95CD4E5145E5");

                    b.HasIndex("TemplateId");

                    b.ToTable("audit_site_template", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.Airport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AirSide")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("ComercialArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("TerminalSection")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__airport__3213E83F178E14CD");

                    b.HasIndex(new[] { "Code" }, "UQ__airport__357D4CF90A3E0150")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "UQ__airport__72E12F1B1E2BB23C")
                        .IsUnique();

                    b.ToTable("airport", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AzureAdObjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("azure_ad_object_id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("PK__app_user__3213E83F1159EBF7");

                    b.HasIndex(new[] { "AzureAdObjectId" }, "UQ__app_user__0E42BF72C6C8469F")
                        .IsUnique();

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.AuditAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("content_type");

                    b.Property<long>("ExecutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("execution_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<DateTime?>("UploadedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("Id")
                        .HasName("PK__audit_at__3213E83F3A4458CE");

                    b.HasIndex("ExecutionId");

                    b.ToTable("audit_attachment", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.AuditExecution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AcceptanceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("acceptance_date");

                    b.Property<long>("AuditorId")
                        .HasColumnType("bigint")
                        .HasColumnName("auditor_id");

                    b.Property<DateTime>("OriginalAuditDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("original_audit_date");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("rejection_reason");

                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("submission_date");

                    b.HasKey("Id")
                        .HasName("PK__audit_ex__3213E83FA1316016");

                    b.HasIndex("AuditorId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex(new[] { "Status" }, "idx_execution_status");

                    b.ToTable("audit_execution", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.AuditExecutionResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CalculatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("calculated_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("CompliantCount")
                        .HasColumnType("int")
                        .HasColumnName("compliant_count");

                    b.Property<long>("ExecutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("execution_id");

                    b.Property<int>("NonCompliantCount")
                        .HasColumnType("int")
                        .HasColumnName("non_compliant_count");

                    b.Property<int?>("NotApplicableCount")
                        .HasColumnType("int")
                        .HasColumnName("not_applicable_count");

                    b.Property<decimal>("ScorePercentage")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("score_percentage");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int")
                        .HasColumnName("total_questions");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExecutionId" }, "UQ_execution_result_execution")
                        .IsUnique();

                    b.ToTable("audit_execution_result", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.AuditResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("comment");

                    b.Property<bool?>("Compliant")
                        .HasColumnType("bit")
                        .HasColumnName("compliant");

                    b.Property<long>("ExecutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("execution_id");

                    b.Property<long?>("SelectedOptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("selected_option_id");

                    b.Property<long>("TemplateItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_item_id");

                    b.HasKey("Id")
                        .HasName("PK__audit_re__3213E83F55E5FE9F");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("TemplateItemId");

                    b.HasIndex(new[] { "ExecutionId" }, "idx_response_execution");

                    b.ToTable("audit_response", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.AuditResponseAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<long>("ResponseId")
                        .HasColumnType("bigint")
                        .HasColumnName("response_id");

                    b.Property<DateTime>("UploadedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("Id");

                    b.HasIndex("ResponseId");

                    b.ToTable("audit_response_attachment", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.AuditSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_date");

                    b.Property<string>("ModificationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("modification_reason");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_date");

                    b.Property<long>("SchedulerId")
                        .HasColumnType("bigint")
                        .HasColumnName("scheduler_id");

                    b.Property<long>("SiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("PK__audit_sc__3213E83F48C5834A");

                    b.HasIndex("SchedulerId");

                    b.HasIndex("SiteId");

                    b.HasIndex("TemplateId");

                    b.HasIndex(new[] { "Status" }, "idx_schedule_status");

                    b.ToTable("audit_schedule", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.AuditSite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AirportId")
                        .HasColumnType("bigint")
                        .HasColumnName("airport_id");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("department_id");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__audit_si__3213E83F2E69B5A2");

                    b.HasIndex("AirportId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepartmentId");

                    b.ToTable("audit_site", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.AuditTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("PK__audit_te__3213E83FB8A2B4CB");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "Name" }, "UQ__audit_te__72E12F1B84BFD71C")
                        .IsUnique();

                    b.ToTable("audit_template", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.AuditTemplateItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Mandatory")
                        .HasColumnType("bit")
                        .HasColumnName("mandatory");

                    b.Property<long>("QuestionBankId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_bank_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasColumnName("sequence");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("PK__audit_te__3213E83F30483F4F");

                    b.HasIndex("QuestionBankId");

                    b.HasIndex(new[] { "TemplateId" }, "idx_template_item_template");

                    b.ToTable("audit_template_item", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__departme__3213E83FADB797C3");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<long>("RecipientId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipient_id");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_date");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK__notifica__3213E83FAD279980");

                    b.HasIndex(new[] { "RecipientId" }, "idx_notification_recipient");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.QuestionBank", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("question_text");

                    b.Property<long>("QuestionTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_type_id");

                    b.Property<string>("ResponsibleContractor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("responsible_contractor");

                    b.Property<string>("ServiceStandardRecommendation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("service_standard_recommendation");

                    b.HasKey("Id")
                        .HasName("PK__question__3213E83FD16E9283");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("QuestionTypeId");

                    b.HasIndex(new[] { "CategoryId" }, "idx_question_bank_category");

                    b.ToTable("question_bank", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.QuestionBankOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("option_text");

                    b.Property<string>("OptionValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("option_value");

                    b.Property<long>("QuestionBankId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_bank_id");

                    b.Property<bool>("RequiresReason")
                        .HasColumnType("bit")
                        .HasColumnName("requires_reason");

                    b.HasKey("Id")
                        .HasName("PK__question__3213E83F9030CCB8");

                    b.HasIndex("QuestionBankId");

                    b.ToTable("question_bank_option", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.QuestionBankReason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("QuestionBankId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_bank_id");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("reason_text");

                    b.HasKey("Id")
                        .HasName("PK__question__3213E83F6ED53A41");

                    b.HasIndex("QuestionBankId");

                    b.ToTable("question_bank_reason", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.QuestionCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__question__3213E83F12F8191F");

                    b.HasIndex(new[] { "Name" }, "UQ__question__72E12F1B59B99650")
                        .IsUnique();

                    b.ToTable("question_category", (string)null);
                });

            modelBuilder.Entity("Auditor.Models.QuestionType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__question__3213E83F70F1D122");

                    b.HasIndex(new[] { "Name" }, "UQ__question__72E12F1B2F93D81A")
                        .IsUnique();

                    b.ToTable("question_type", (string)null);
                });

            modelBuilder.Entity("AuditResponseReason", b =>
                {
                    b.HasOne("Auditor.Models.QuestionBankReason", null)
                        .WithMany()
                        .HasForeignKey("ReasonId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_res__reaso__123EB7A3");

                    b.HasOne("Auditor.Models.AuditResponse", null)
                        .WithMany()
                        .HasForeignKey("ResponseId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_res__respo__114A936A");
                });

            modelBuilder.Entity("AuditScheduleAuditor", b =>
                {
                    b.HasOne("Auditor.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AuditorId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_sch__audit__04E4BC85");

                    b.HasOne("Auditor.Models.AuditSchedule", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_sch__sched__03F0984C");
                });

            modelBuilder.Entity("AuditSiteTemplate", b =>
                {
                    b.HasOne("Auditor.Models.AuditSite", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_sit__site___797309D9");

                    b.HasOne("Auditor.Models.AuditTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_sit__templ__7A672E12");
                });

            modelBuilder.Entity("Auditor.Models.AuditAttachment", b =>
                {
                    b.HasOne("Auditor.Models.AuditExecution", "Execution")
                        .WithMany("AuditAttachments")
                        .HasForeignKey("ExecutionId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_att__execu__160F4887");

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("Auditor.Models.AuditExecution", b =>
                {
                    b.HasOne("Auditor.Models.AppUser", "Auditor")
                        .WithMany("AuditExecutions")
                        .HasForeignKey("AuditorId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_exe__audit__09A971A2");

                    b.HasOne("Auditor.Models.AuditSchedule", "Schedule")
                        .WithMany("AuditExecutions")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_exe__sched__08B54D69");

                    b.Navigation("Auditor");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Auditor.Models.AuditExecutionResult", b =>
                {
                    b.HasOne("Auditor.Models.AuditExecution", "Execution")
                        .WithOne("AuditExecutionResult")
                        .HasForeignKey("Auditor.Models.AuditExecutionResult", "ExecutionId")
                        .IsRequired()
                        .HasConstraintName("FK_execution_result_execution");

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("Auditor.Models.AuditResponse", b =>
                {
                    b.HasOne("Auditor.Models.AuditExecution", "Execution")
                        .WithMany("AuditResponses")
                        .HasForeignKey("ExecutionId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_res__execu__0C85DE4D");

                    b.HasOne("Auditor.Models.QuestionBankOption", "SelectedOption")
                        .WithMany("AuditResponses")
                        .HasForeignKey("SelectedOptionId")
                        .HasConstraintName("FK__audit_res__selec__0E6E26BF");

                    b.HasOne("Auditor.Models.AuditTemplateItem", "TemplateItem")
                        .WithMany("AuditResponses")
                        .HasForeignKey("TemplateItemId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_res__templ__0D7A0286");

                    b.Navigation("Execution");

                    b.Navigation("SelectedOption");

                    b.Navigation("TemplateItem");
                });

            modelBuilder.Entity("Auditor.Models.AuditResponseAttachment", b =>
                {
                    b.HasOne("Auditor.Models.AuditResponse", "Response")
                        .WithMany("AuditResponseAttachments")
                        .HasForeignKey("ResponseId")
                        .IsRequired()
                        .HasConstraintName("FK_response_attachment_response");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("Auditor.Models.AuditSchedule", b =>
                {
                    b.HasOne("Auditor.Models.AppUser", "Scheduler")
                        .WithMany("AuditSchedules")
                        .HasForeignKey("SchedulerId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_sch__sched__01142BA1");

                    b.HasOne("Auditor.Models.AuditSite", "Site")
                        .WithMany("AuditSchedules")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_sch__site___00200768");

                    b.HasOne("Auditor.Models.AuditTemplate", "Template")
                        .WithMany("AuditSchedules")
                        .HasForeignKey("TemplateId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_sch__templ__7F2BE32F");

                    b.Navigation("Scheduler");

                    b.Navigation("Site");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Auditor.Models.AuditSite", b =>
                {
                    b.HasOne("Auditor.Models.Airport", "Airport")
                        .WithMany("AuditSites")
                        .HasForeignKey("AirportId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_sit__airpo__74AE54BC");

                    b.HasOne("Auditor.Models.AppUser", "CreatedByNavigation")
                        .WithMany("AuditSites")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__audit_sit__creat__76969D2E");

                    b.HasOne("Auditor.Models.Department", "Department")
                        .WithMany("AuditSites")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_sit__depar__75A278F5");

                    b.Navigation("Airport");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Auditor.Models.AuditTemplate", b =>
                {
                    b.HasOne("Auditor.Models.AppUser", "CreatedByNavigation")
                        .WithMany("AuditTemplates")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__audit_tem__creat__6C190EBB");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("Auditor.Models.AuditTemplateItem", b =>
                {
                    b.HasOne("Auditor.Models.QuestionBank", "QuestionBank")
                        .WithMany("AuditTemplateItems")
                        .HasForeignKey("QuestionBankId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_tem__quest__6FE99F9F");

                    b.HasOne("Auditor.Models.AuditTemplate", "Template")
                        .WithMany("AuditTemplateItems")
                        .HasForeignKey("TemplateId")
                        .IsRequired()
                        .HasConstraintName("FK__audit_tem__templ__6EF57B66");

                    b.Navigation("QuestionBank");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Auditor.Models.Notification", b =>
                {
                    b.HasOne("Auditor.Models.AppUser", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .IsRequired()
                        .HasConstraintName("FK__notificat__recip__1AD3FDA4");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Auditor.Models.QuestionBank", b =>
                {
                    b.HasOne("Auditor.Models.QuestionCategory", "Category")
                        .WithMany("QuestionBanks")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__question___categ__5FB337D6");

                    b.HasOne("Auditor.Models.AppUser", "CreatedByNavigation")
                        .WithMany("QuestionBanks")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__question___creat__619B8048");

                    b.HasOne("Auditor.Models.QuestionType", "QuestionType")
                        .WithMany("QuestionBanks")
                        .HasForeignKey("QuestionTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__question___quest__60A75C0F");

                    b.Navigation("Category");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("Auditor.Models.QuestionBankOption", b =>
                {
                    b.HasOne("Auditor.Models.QuestionBank", "QuestionBank")
                        .WithMany("QuestionBankOptions")
                        .HasForeignKey("QuestionBankId")
                        .IsRequired()
                        .HasConstraintName("FK__question___quest__6477ECF3");

                    b.Navigation("QuestionBank");
                });

            modelBuilder.Entity("Auditor.Models.QuestionBankReason", b =>
                {
                    b.HasOne("Auditor.Models.QuestionBank", "QuestionBank")
                        .WithMany("QuestionBankReasons")
                        .HasForeignKey("QuestionBankId")
                        .IsRequired()
                        .HasConstraintName("FK__question___quest__6754599E");

                    b.Navigation("QuestionBank");
                });

            modelBuilder.Entity("Auditor.Models.Airport", b =>
                {
                    b.Navigation("AuditSites");
                });

            modelBuilder.Entity("Auditor.Models.AppUser", b =>
                {
                    b.Navigation("AuditExecutions");

                    b.Navigation("AuditSchedules");

                    b.Navigation("AuditSites");

                    b.Navigation("AuditTemplates");

                    b.Navigation("Notifications");

                    b.Navigation("QuestionBanks");
                });

            modelBuilder.Entity("Auditor.Models.AuditExecution", b =>
                {
                    b.Navigation("AuditAttachments");

                    b.Navigation("AuditExecutionResult");

                    b.Navigation("AuditResponses");
                });

            modelBuilder.Entity("Auditor.Models.AuditResponse", b =>
                {
                    b.Navigation("AuditResponseAttachments");
                });

            modelBuilder.Entity("Auditor.Models.AuditSchedule", b =>
                {
                    b.Navigation("AuditExecutions");
                });

            modelBuilder.Entity("Auditor.Models.AuditSite", b =>
                {
                    b.Navigation("AuditSchedules");
                });

            modelBuilder.Entity("Auditor.Models.AuditTemplate", b =>
                {
                    b.Navigation("AuditSchedules");

                    b.Navigation("AuditTemplateItems");
                });

            modelBuilder.Entity("Auditor.Models.AuditTemplateItem", b =>
                {
                    b.Navigation("AuditResponses");
                });

            modelBuilder.Entity("Auditor.Models.Department", b =>
                {
                    b.Navigation("AuditSites");
                });

            modelBuilder.Entity("Auditor.Models.QuestionBank", b =>
                {
                    b.Navigation("AuditTemplateItems");

                    b.Navigation("QuestionBankOptions");

                    b.Navigation("QuestionBankReasons");
                });

            modelBuilder.Entity("Auditor.Models.QuestionBankOption", b =>
                {
                    b.Navigation("AuditResponses");
                });

            modelBuilder.Entity("Auditor.Models.QuestionCategory", b =>
                {
                    b.Navigation("QuestionBanks");
                });

            modelBuilder.Entity("Auditor.Models.QuestionType", b =>
                {
                    b.Navigation("QuestionBanks");
                });
#pragma warning restore 612, 618
        }
    }
}
