// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class Airport
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public string Location { get; set; }

    public string AirSide { get; set; }

    public string ComercialArea { get; set; }

    public string TerminalSection { get; set; }

    public virtual ICollection<AuditSite> AuditSites { get; set; } = new List<AuditSite>();
}
