// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class AppUser
{
    public long Id { get; set; }

    public Guid AzureAdObjectId { get; set; }

    public string PasswordHash { get; set; }

    public string DisplayName { get; set; }

    public string? Role { get; set; }

    public string Email { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<AuditExecution> AuditExecutions { get; set; } = new List<AuditExecution>();

    public virtual ICollection<AuditSchedule> AuditSchedules { get; set; } = new List<AuditSchedule>();

    public virtual ICollection<AuditSite> AuditSites { get; set; } = new List<AuditSite>();

    public virtual ICollection<AuditTemplate> AuditTemplates { get; set; } = new List<AuditTemplate>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<QuestionBank> QuestionBanks { get; set; } = new List<QuestionBank>();

    public virtual ICollection<AuditSchedule> Schedules { get; set; } = new List<AuditSchedule>();
}
