// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class AsqUpload
{
    public long Id { get; set; }

    public string FileName { get; set; }

    public string FileUrl { get; set; }

    public long UploadedBy { get; set; }

    public DateTime UploadDate { get; set; }

    public bool Processed { get; set; }

    public virtual AppUser UploadedByNavigation { get; set; }
}
