// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class AuditAttachment
{
    public long Id { get; set; }

    public long ExecutionId { get; set; }

    public string FileName { get; set; }

    public string FileUrl { get; set; }

    public string ContentType { get; set; }

    public long? FileSize { get; set; }

    public DateTime? UploadedDate { get; set; }

    public virtual AuditExecution Execution { get; set; }
}
