// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class AuditResponseAttachment
{
    public long Id { get; set; }

    public long ResponseId { get; set; }

    public string FileName { get; set; }

    public string FileUrl { get; set; }

    public string ContentType { get; set; }

    public long? FileSize { get; set; }

    public DateTime UploadedDate { get; set; }

    public virtual AuditResponse Response { get; set; }
}
