// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class AuditExecution
{
    public long Id { get; set; }

    public long ScheduleId { get; set; }

    public long AuditorId { get; set; }

    public string Status { get; set; }

    public DateTime? AcceptanceDate { get; set; }

    public string RejectionReason { get; set; }

    public DateTime? SubmissionDate { get; set; }

    public DateTime OriginalAuditDate { get; set; }

    public virtual ICollection<AuditAttachment> AuditAttachments { get; set; } = new List<AuditAttachment>();

    public virtual AuditExecutionResult AuditExecutionResult { get; set; }

    public virtual ICollection<AuditResponse> AuditResponses { get; set; } = new List<AuditResponse>();

    public virtual AppUser Auditor { get; set; }

    public virtual AuditSchedule Schedule { get; set; }
}
