// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class AuditTemplateItem
{
    public long Id { get; set; }

    public long TemplateId { get; set; }

    public long QuestionBankId { get; set; }

    public int Sequence { get; set; }

    public bool Mandatory { get; set; }

    public long? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual ICollection<AuditResponse> AuditResponses { get; set; } = new List<AuditResponse>();

    public virtual QuestionBank QuestionBank { get; set; }

    public virtual AuditTemplate Template { get; set; }
}
