// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class AuditExecutionResult
{
    public long Id { get; set; }

    public long ExecutionId { get; set; }

    public int TotalQuestions { get; set; }

    public int CompliantCount { get; set; }

    public int NonCompliantCount { get; set; }

    public int? NotApplicableCount { get; set; }

    public decimal ScorePercentage { get; set; }

    public DateTime CalculatedDate { get; set; }

    public virtual AuditExecution Execution { get; set; }
}
