// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Auditor.Models;

public partial class AuditorContext : DbContext
{
    public AuditorContext()
    {
    }

    public AuditorContext(DbContextOptions<AuditorContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Airport> Airports { get; set; }

    public virtual DbSet<AppUser> AppUsers { get; set; }

    public virtual DbSet<AuditAttachment> AuditAttachments { get; set; }

    public virtual DbSet<AuditExecution> AuditExecutions { get; set; }

    public virtual DbSet<AuditExecutionResult> AuditExecutionResults { get; set; }

    public virtual DbSet<AuditResponse> AuditResponses { get; set; }

    public virtual DbSet<AuditResponseAttachment> AuditResponseAttachments { get; set; }

    public virtual DbSet<AuditSchedule> AuditSchedules { get; set; }

    public virtual DbSet<AuditSite> AuditSites { get; set; }

    public virtual DbSet<AuditTemplate> AuditTemplates { get; set; }

    public virtual DbSet<AuditTemplateItem> AuditTemplateItems { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<QuestionBank> QuestionBanks { get; set; }

    public virtual DbSet<QuestionBankOption> QuestionBankOptions { get; set; }

    public virtual DbSet<QuestionBankReason> QuestionBankReasons { get; set; }

    public virtual DbSet<QuestionCategory> QuestionCategories { get; set; }

    public virtual DbSet<QuestionType> QuestionTypes { get; set; }

   
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Airport>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__airport__3213E83F178E14CD");

            entity.ToTable("airport");

            entity.HasIndex(e => e.Code, "UQ__airport__357D4CF90A3E0150").IsUnique();

            entity.HasIndex(e => e.Name, "UQ__airport__72E12F1B1E2BB23C").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("code");
            entity.Property(e => e.Location)
                .HasMaxLength(255)
                .HasColumnName("location");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<AppUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__app_user__3213E83F1159EBF7");

            entity.ToTable("app_user");

            entity.HasIndex(e => e.AzureAdObjectId, "UQ__app_user__0E42BF72C6C8469F").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AzureAdObjectId).HasColumnName("azure_ad_object_id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_date");
            entity.Property(e => e.DisplayName)
                .HasMaxLength(255)
                .HasColumnName("display_name");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.PasswordHash)
                .HasMaxLength(255)
                .HasColumnName("password_hash");
            entity.Property(e => e.Role)
                .HasMaxLength(50)
                .HasColumnName("role");
        });

        modelBuilder.Entity<AuditAttachment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__audit_at__3213E83F3A4458CE");

            entity.ToTable("audit_attachment");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ContentType)
                .HasMaxLength(100)
                .HasColumnName("content_type");
            entity.Property(e => e.ExecutionId).HasColumnName("execution_id");
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("file_name");
            entity.Property(e => e.FileSize).HasColumnName("file_size");
            entity.Property(e => e.FileUrl)
                .HasMaxLength(500)
                .HasColumnName("file_url");
            entity.Property(e => e.UploadedDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("uploaded_date");

            entity.HasOne(d => d.Execution).WithMany(p => p.AuditAttachments)
                .HasForeignKey(d => d.ExecutionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__audit_att__execu__160F4887");
        });

        modelBuilder.Entity<AuditExecution>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__audit_ex__3213E83FA1316016");

            entity.ToTable("audit_execution");

            entity.HasIndex(e => e.Status, "idx_execution_status");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AcceptanceDate).HasColumnName("acceptance_date");
            entity.Property(e => e.AuditorId).HasColumnName("auditor_id");
            entity.Property(e => e.OriginalAuditDate).HasColumnName("original_audit_date");
            entity.Property(e => e.RejectionReason)
                .HasMaxLength(2000)
                .HasColumnName("rejection_reason");
            entity.Property(e => e.ScheduleId).HasColumnName("schedule_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.SubmissionDate).HasColumnName("submission_date");

            entity.HasOne(d => d.Auditor).WithMany(p => p.AuditExecutions)
                .HasForeignKey(d => d.AuditorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__audit_exe__audit__09A971A2");

            entity.HasOne(d => d.Schedule).WithMany(p => p.AuditExecutions)
                .HasForeignKey(d => d.ScheduleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__audit_exe__sched__08B54D69");
        });

        modelBuilder.Entity<AuditExecutionResult>(entity =>
        {
            entity.ToTable("audit_execution_result");

            entity.HasIndex(e => e.ExecutionId, "UQ_execution_result_execution").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CalculatedDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("calculated_date");
            entity.Property(e => e.CompliantCount).HasColumnName("compliant_count");
            entity.Property(e => e.ExecutionId).HasColumnName("execution_id");
            entity.Property(e => e.NonCompliantCount).HasColumnName("non_compliant_count");
            entity.Property(e => e.NotApplicableCount).HasColumnName("not_applicable_count");
            entity.Property(e => e.ScorePercentage)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("score_percentage");
            entity.Property(e => e.TotalQuestions).HasColumnName("total_questions");

            entity.HasOne(d => d.Execution).WithOne(p => p.AuditExecutionResult)
                .HasForeignKey<AuditExecutionResult>(d => d.ExecutionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_execution_result_execution");
        });

        modelBuilder.Entity<AuditResponse>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__audit_re__3213E83F55E5FE9F");

            entity.ToTable("audit_response");

            entity.HasIndex(e => e.ExecutionId, "idx_response_execution");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Comment)
                .HasMaxLength(2000)
                .HasColumnName("comment");
            entity.Property(e => e.Compliant).HasColumnName("compliant");
            entity.Property(e => e.ExecutionId).HasColumnName("execution_id");
            entity.Property(e => e.SelectedOptionId).HasColumnName("selected_option_id");
            entity.Property(e => e.TemplateItemId).HasColumnName("template_item_id");

            entity.HasOne(d => d.Execution).WithMany(p => p.AuditResponses)
                .HasForeignKey(d => d.ExecutionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__audit_res__execu__0C85DE4D");

            entity.HasOne(d => d.SelectedOption).WithMany(p => p.AuditResponses)
                .HasForeignKey(d => d.SelectedOptionId)
                .HasConstraintName("FK__audit_res__selec__0E6E26BF");

            entity.HasOne(d => d.TemplateItem).WithMany(p => p.AuditResponses)
                .HasForeignKey(d => d.TemplateItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__audit_res__templ__0D7A0286");

            entity.HasMany(d => d.Reasons).WithMany(p => p.Responses)
                .UsingEntity<Dictionary<string, object>>(
                    "AuditResponseReason",
                    r => r.HasOne<QuestionBankReason>().WithMany()
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__audit_res__reaso__123EB7A3"),
                    l => l.HasOne<AuditResponse>().WithMany()
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__audit_res__respo__114A936A"),
                    j =>
                    {
                        j.HasKey("ResponseId", "ReasonId").HasName("PK__audit_re__B3AA63C32753E0CD");
                        j.ToTable("audit_response_reason");
                        j.IndexerProperty<long>("ResponseId").HasColumnName("response_id");
                        j.IndexerProperty<long>("ReasonId").HasColumnName("reason_id");
                    });
        });

        modelBuilder.Entity<AuditResponseAttachment>(entity =>
        {
            entity.ToTable("audit_response_attachment");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ContentType)
                .HasMaxLength(100)
                .HasColumnName("content_type");
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("file_name");
            entity.Property(e => e.FileSize).HasColumnName("file_size");
            entity.Property(e => e.FileUrl)
                .HasMaxLength(500)
                .HasColumnName("file_url");
            entity.Property(e => e.ResponseId).HasColumnName("response_id");
            entity.Property(e => e.UploadedDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("uploaded_date");

            entity.HasOne(d => d.Response).WithMany(p => p.AuditResponseAttachments)
                .HasForeignKey(d => d.ResponseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_response_attachment_response");
        });

        modelBuilder.Entity<AuditSchedule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__audit_sc__3213E83F48C5834A");

            entity.ToTable("audit_schedule");

            entity.HasIndex(e => e.Status, "idx_schedule_status");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CancellationReason)
                .HasMaxLength(1000)
                .HasColumnName("cancellation_reason");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_date");
            entity.Property(e => e.DueDate).HasColumnName("due_date");
            entity.Property(e => e.ModificationReason)
                .HasMaxLength(1000)
                .HasColumnName("modification_reason");
            entity.Property(e => e.ScheduledDate).HasColumnName("scheduled_date");
            entity.Property(e => e.SchedulerId).HasColumnName("scheduler_id");
            entity.Property(e => e.SiteId).HasColumnName("site_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.TemplateId).HasColumnName("template_id");

            entity.HasOne(d => d.Scheduler).WithMany(p => p.AuditSchedules)
                .HasForeignKey(d => d.SchedulerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__audit_sch__sched__01142BA1");

            entity.HasOne(d => d.Site).WithMany(p => p.AuditSchedules)
                .HasForeignKey(d => d.SiteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__audit_sch__site___00200768");

            entity.HasOne(d => d.Template).WithMany(p => p.AuditSchedules)
                .HasForeignKey(d => d.TemplateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__audit_sch__templ__7F2BE32F");

            entity.HasMany(d => d.Auditors).WithMany(p => p.Schedules)
                .UsingEntity<Dictionary<string, object>>(
                    "AuditScheduleAuditor",
                    r => r.HasOne<AppUser>().WithMany()
                        .HasForeignKey("AuditorId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__audit_sch__audit__04E4BC85"),
                    l => l.HasOne<AuditSchedule>().WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__audit_sch__sched__03F0984C"),
                    j =>
                    {
                        j.HasKey("ScheduleId", "AuditorId").HasName("PK__audit_sc__BD9E29F05A8F4534");
                        j.ToTable("audit_schedule_auditor");
                        j.IndexerProperty<long>("ScheduleId").HasColumnName("schedule_id");
                        j.IndexerProperty<long>("AuditorId").HasColumnName("auditor_id");
                    });
        });

        modelBuilder.Entity<AuditSite>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__audit_si__3213E83F2E69B5A2");

            entity.ToTable("audit_site");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AirportId).HasColumnName("airport_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_date");
            entity.Property(e => e.DepartmentId).HasColumnName("department_id");
            entity.Property(e => e.Location)
                .HasMaxLength(255)
                .HasColumnName("location");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");

            entity.HasOne(d => d.Airport).WithMany(p => p.AuditSites)
                .HasForeignKey(d => d.AirportId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__audit_sit__airpo__74AE54BC");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.AuditSites)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__audit_sit__creat__76969D2E");

            entity.HasOne(d => d.Department).WithMany(p => p.AuditSites)
                .HasForeignKey(d => d.DepartmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__audit_sit__depar__75A278F5");

            entity.HasMany(d => d.Templates).WithMany(p => p.Sites)
                .UsingEntity<Dictionary<string, object>>(
                    "AuditSiteTemplate",
                    r => r.HasOne<AuditTemplate>().WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__audit_sit__templ__7A672E12"),
                    l => l.HasOne<AuditSite>().WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__audit_sit__site___797309D9"),
                    j =>
                    {
                        j.HasKey("SiteId", "TemplateId").HasName("PK__audit_si__39CB95CD4E5145E5");
                        j.ToTable("audit_site_template");
                        j.IndexerProperty<long>("SiteId").HasColumnName("site_id");
                        j.IndexerProperty<long>("TemplateId").HasColumnName("template_id");
                    });
        });

        modelBuilder.Entity<AuditTemplate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__audit_te__3213E83FB8A2B4CB");

            entity.ToTable("audit_template");

            entity.HasIndex(e => e.Name, "UQ__audit_te__72E12F1B84BFD71C").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.Version)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("version");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.AuditTemplates)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__audit_tem__creat__6C190EBB");
        });

        modelBuilder.Entity<AuditTemplateItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__audit_te__3213E83F30483F4F");

            entity.ToTable("audit_template_item");

            entity.HasIndex(e => e.TemplateId, "idx_template_item_template");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Mandatory).HasColumnName("mandatory");
            entity.Property(e => e.QuestionBankId).HasColumnName("question_bank_id");
            entity.Property(e => e.Sequence).HasColumnName("sequence");
            entity.Property(e => e.TemplateId).HasColumnName("template_id");

            entity.HasOne(d => d.QuestionBank).WithMany(p => p.AuditTemplateItems)
                .HasForeignKey(d => d.QuestionBankId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__audit_tem__quest__6FE99F9F");

            entity.HasOne(d => d.Template).WithMany(p => p.AuditTemplateItems)
                .HasForeignKey(d => d.TemplateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__audit_tem__templ__6EF57B66");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__departme__3213E83FADB797C3");

            entity.ToTable("department");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__notifica__3213E83FAD279980");

            entity.ToTable("notification");

            entity.HasIndex(e => e.RecipientId, "idx_notification_recipient");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.EntityId).HasColumnName("entity_id");
            entity.Property(e => e.EntityType)
                .HasMaxLength(100)
                .HasColumnName("entity_type");
            entity.Property(e => e.IsRead).HasColumnName("is_read");
            entity.Property(e => e.Message)
                .IsRequired()
                .HasColumnName("message");
            entity.Property(e => e.RecipientId).HasColumnName("recipient_id");
            entity.Property(e => e.SentDate).HasColumnName("sent_date");
            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("subject");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("type");

            entity.HasOne(d => d.Recipient).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.RecipientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__notificat__recip__1AD3FDA4");
        });

        modelBuilder.Entity<QuestionBank>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__question__3213E83FD16E9283");

            entity.ToTable("question_bank");

            entity.HasIndex(e => e.CategoryId, "idx_question_bank_category");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CategoryId).HasColumnName("category_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_date");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.QuestionText)
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnName("question_text");
            entity.Property(e => e.QuestionTypeId).HasColumnName("question_type_id");
            entity.Property(e => e.ResponsibleContractor)
                .HasMaxLength(255)
                .HasColumnName("responsible_contractor");
            entity.Property(e => e.ServiceStandardRecommendation)
                .HasMaxLength(2000)
                .HasColumnName("service_standard_recommendation");

            entity.HasOne(d => d.Category).WithMany(p => p.QuestionBanks)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__question___categ__5FB337D6");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.QuestionBanks)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__question___creat__619B8048");

            entity.HasOne(d => d.QuestionType).WithMany(p => p.QuestionBanks)
                .HasForeignKey(d => d.QuestionTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__question___quest__60A75C0F");
        });

        modelBuilder.Entity<QuestionBankOption>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__question__3213E83F9030CCB8");

            entity.ToTable("question_bank_option");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.DisplayOrder).HasColumnName("display_order");
            entity.Property(e => e.OptionText)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("option_text");
            entity.Property(e => e.OptionValue)
                .HasMaxLength(100)
                .HasColumnName("option_value");
            entity.Property(e => e.QuestionBankId).HasColumnName("question_bank_id");
            entity.Property(e => e.RequiresReason).HasColumnName("requires_reason");

            entity.HasOne(d => d.QuestionBank).WithMany(p => p.QuestionBankOptions)
                .HasForeignKey(d => d.QuestionBankId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__question___quest__6477ECF3");
        });

        modelBuilder.Entity<QuestionBankReason>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__question__3213E83F6ED53A41");

            entity.ToTable("question_bank_reason");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.QuestionBankId).HasColumnName("question_bank_id");
            entity.Property(e => e.ReasonText)
                .IsRequired()
                .HasMaxLength(1000)
                .HasColumnName("reason_text");

            entity.HasOne(d => d.QuestionBank).WithMany(p => p.QuestionBankReasons)
                .HasForeignKey(d => d.QuestionBankId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__question___quest__6754599E");
        });

        modelBuilder.Entity<QuestionCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__question__3213E83F12F8191F");

            entity.ToTable("question_category");

            entity.HasIndex(e => e.Name, "UQ__question__72E12F1B59B99650").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<QuestionType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__question__3213E83F70F1D122");

            entity.ToTable("question_type");

            entity.HasIndex(e => e.Name, "UQ__question__72E12F1B2F93D81A").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
