// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class AuditTemplate
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Version { get; set; }

    public bool IsActive { get; set; }

    public long CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<AuditSchedule> AuditSchedules { get; set; } = new List<AuditSchedule>();

    public virtual ICollection<AuditTemplateItem> AuditTemplateItems { get; set; } = new List<AuditTemplateItem>();

    public virtual AppUser CreatedByNavigation { get; set; }

    public virtual ICollection<AuditSite> Sites { get; set; } = new List<AuditSite>();
}
