// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class AuditSite
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string Location { get; set; }

    public string Status { get; set; }

    public long AirportId { get; set; }

    public long DepartmentId { get; set; }

    public long CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Airport Airport { get; set; }

    public virtual ICollection<AuditSchedule> AuditSchedules { get; set; } = new List<AuditSchedule>();

    public virtual AppUser CreatedByNavigation { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<AuditTemplate> Templates { get; set; } = new List<AuditTemplate>();
}
