// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class AuditSchedule
{
    public long Id { get; set; }

    public long TemplateId { get; set; }

    public long SiteId { get; set; }

    public long SchedulerId { get; set; }

    public DateTime ScheduledDate { get; set; }

    public DateTime DueDate { get; set; }

    public string Status { get; set; }

    public string ModificationReason { get; set; }

    public string CancellationReason { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<AuditExecution> AuditExecutions { get; set; } = new List<AuditExecution>();

    public virtual AppUser Scheduler { get; set; }

    public virtual AuditSite Site { get; set; }

    public virtual AuditTemplate Template { get; set; }

    public virtual ICollection<AppUser> Auditors { get; set; } = new List<AppUser>();
}
