// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class AuditResponse
{
    public long Id { get; set; }

    public long ExecutionId { get; set; }

    public long TemplateItemId { get; set; }

    public long? SelectedOptionId { get; set; }

    public string Comment { get; set; }

    public bool? Compliant { get; set; }

    public virtual ICollection<AuditResponseAttachment> AuditResponseAttachments { get; set; } = new List<AuditResponseAttachment>();

    public virtual AuditExecution Execution { get; set; }

    public virtual QuestionBankOption SelectedOption { get; set; }

    public virtual AuditTemplateItem TemplateItem { get; set; }

    public virtual ICollection<QuestionBankReason> Reasons { get; set; } = new List<QuestionBankReason>();
}
