// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class Notification
{
    public long Id { get; set; }

    public long RecipientId { get; set; }

    public string Subject { get; set; }

    public string Message { get; set; }

    public string Type { get; set; }

    public string EntityType { get; set; }

    public long? EntityId { get; set; }

    public DateTime? SentDate { get; set; }

    public bool IsRead { get; set; }

    public virtual AppUser Recipient { get; set; }
}
