// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class QuestionBankReason
{
    public long Id { get; set; }

    public long QuestionBankId { get; set; }

    public string ReasonText { get; set; }

    public virtual QuestionBank QuestionBank { get; set; }

    public virtual ICollection<AuditResponse> Responses { get; set; } = new List<AuditResponse>();
}
