// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class QuestionBank
{
    public long Id { get; set; }

    public string QuestionText { get; set; }

    public long CategoryId { get; set; }

    public long QuestionTypeId { get; set; }

    public string ServiceStandardRecommendation { get; set; }

    public string ResponsibleContractor { get; set; }

    public bool IsActive { get; set; }

    public long CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<AuditTemplateItem> AuditTemplateItems { get; set; } = new List<AuditTemplateItem>();

    public virtual QuestionCategory Category { get; set; }

    public virtual AppUser CreatedByNavigation { get; set; }

    public virtual ICollection<QuestionBankOption> QuestionBankOptions { get; set; } = new List<QuestionBankOption>();

    public virtual ICollection<QuestionBankReason> QuestionBankReasons { get; set; } = new List<QuestionBankReason>();

    public virtual QuestionType QuestionType { get; set; }
}
