// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class QuestionBankOption
{
    public long Id { get; set; }

    public long QuestionBankId { get; set; }

    public string OptionText { get; set; }

    public string OptionValue { get; set; }

    public int DisplayOrder { get; set; }

    public bool RequiresReason { get; set; }

    public virtual ICollection<AuditResponse> AuditResponses { get; set; } = new List<AuditResponse>();

    public virtual QuestionBank QuestionBank { get; set; }
}
