// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace Auditor.Models;

public partial class ScheduleChangeRequest
{
    public long Id { get; set; }

    public long ScheduleId { get; set; }

    public long RequestedBy { get; set; }

    public long? AuthorizerId { get; set; }

    public string Reason { get; set; }

    public string Status { get; set; }

    public DateTime RequestDate { get; set; }

    public DateTime? DecisionDate { get; set; }

    public int? EscalationLevel { get; set; }

    public virtual AppUser Authorizer { get; set; }

    public virtual AppUser RequestedByNavigation { get; set; }

    public virtual AuditSchedule Schedule { get; set; }
}
